/// <reference path="../../typings/angularjs/angular.d.ts" />
/// <reference path="../../typings/jquery/jquery.d.ts" />
/// <reference path="../../typings/moment/moment.d.ts" />
/// <reference path="../../typings/chrome/chrome.d.ts" />
/// <reference path="../../typings/lunr/lunr.d.ts" />
/// <reference path="../../typings/log4javascript/log4javascript.d.ts" />
/// <reference path="interfaces/bookmark.ts" />
/// <reference path="controllers/bookmark.ts" />
/// <reference path="directives/bookmark.ts" />
/// <reference path="services/bookmark.ts" />
/// <reference path="interfaces/storage.ts" />
/// <reference path="services/storage.ts" />
//# sourceMappingURL=types.js.map